title: CS284A Project Write-ups
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-relative-links

url: https://geos98.github.io/sp23-proj-webpage-hiro/

exclude:
  - Gemfile.lock
  - Gemfile
  - .gitignore